services:
  db:
    image: postgres:16
    container_name: su_db
    restart: always
    environment:
      POSTGRES_DB: su_takip
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./app
    container_name: su_backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: su_takip
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: