# Generated by Django 5.2.12 on 2026-03-12 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daire_no', models.CharField(max_length=20, unique=True)),
                ('mevcut_metrekup_tuketimi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuketilen_metrekup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odeme_durumu', models.CharField(choices=[('odendi', 'Ödendi'), ('odenmedi', 'Ödenmedi')], default='odenmedi', max_length=20)),
                ('ay', models.PositiveIntegerField()),
                ('yil', models.PositiveIntegerField()),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('daire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturalar', to='daireler.daire')),
            ],
        ),
    ]
