# Generated by Django 5.2.12 on 2026-03-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daireler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatura',
            name='calisma_bedeli',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='tutar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
