# Generated by Django 5.2.12 on 2026-03-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daireler', '0002_fatura_birim_fiyat_fatura_calisma_bedeli_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='calisma_bedeli',
        ),
        migrations.AddField(
            model_name='fatura',
            name='hizmet_bedeli',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
