# Generated by Django 5.2.12 on 2026-03-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daireler', '0004_remove_daire_mevcut_metrekup_tuketimi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='eski_borc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='tarih',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
