# Generated by Django 5.2.12 on 2026-03-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daireler', '0005_fatura_eski_borc_alter_fatura_tarih'),
    ]

    operations = [
        migrations.CreateModel(
            name='IzsuFaturaTakip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilk_endeks', models.FloatField()),
                ('son_endeks', models.FloatField()),
                ('tuketim', models.FloatField()),
                ('ilk_okuma_tarihi', models.CharField(max_length=50)),
                ('son_okuma_tarihi', models.CharField(max_length=50)),
                ('tuketim_gun_sayisi', models.IntegerField()),
                ('fatura_tutari', models.FloatField()),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
