# Generated by Django 5.2.12 on 2026-03-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daireler', '0006_izsufaturatakip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IzsuFaturaTakip',
        ),
    ]
